name: shoppinglist
description: Shoppinglist made with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+42

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pocketbase: ^0.23.0
  provider: ^6.0.5
  email_validator: ^3.0.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.0.17
  flutter_slidable: ^4.0.0
  vibration: ^3.1.0
  vibration_web: ^1.6.5
  theme_provider: ^0.6.0
  intl: ^0.20.2
  fetch_client: ^1.0.2
  http: ^1.1.0
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.0

flutter:
  generate: true # needed for l10n generation
  uses-material-design: true
  assets:
    - assets/race_flag.png

icons_launcher:
  image_path: 'assets/app_logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
    web:
      enable: true
      favicon_path: 'assets/favicon.png'
    macos:
      enable: true
    windows:
      enable: true
